Same test as user_def_default_constructor except the field assigned by the constructor is changed from var to const.  This results in the following internal error from the compiler:
$ chpl user_def_default_constructor_const.chpl
user_def_default_constructor_const.chpl:9: error: ambiguous call 'C()' [functionResolution.cpp:1362]
user_def_default_constructor_const.chpl:1: note: candidates are: C(x: int) [functionResolution.cpp:1378]
error: Indexing list out of bounds [alist.cpp:66]

Steve, I bet you thought you were safe with me way out here in Ohio!  :)


git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@12273 3a8e244f-b0f2-452b-bcba-4c88e055c3ca