Fix exported-fn.chpl for C backend
This fixes code introduced in #20861 where compiling `exported-fn.h`
with gcc gave us:
```
error: function declaration isn~t a prototype [-Werror=strict-prototypes]
static void bar() {
```

Clang does not complain about this.

Testing: the affected test with C and LLVM backends under gasnet.
Signed-off-by: Vassily Litvinov <vasslitvinov@users.noreply.github.com>