Suppress lcals performance testing under cray-prgenv-gnu
This test is failing with an undefined reference to "_ZGVcN4v___exp_finite",
because the driver isn't throwing -lmvec. Suppress it until the driver is fixed