Fix compiler compilation error in view.cpp
[trivial and not reviewed]

After r21946 with gcc 4.4.7, I was getting

view.cpp: In function ‘const char* shortLoc(BaseAST*)’:
view.cpp:1008: error: invalid conversion from ‘const char*’ to ‘char*’

Changed the type of that variable and added a cast
to (const char*) since other compilers might return char*.




git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@21956 3a8e244f-b0f2-452b-bcba-4c88e055c3ca