This is a patch to fixed build errors that occurred because of my loopInvariantCodeMotion commit (R21614)
Specifically: 

- Changed from a using a functor to sort a vector of loops to using a method. 
  The change was originally made because pgi errored saying there was an 
  "undefined reference to `Loop::LoopSort(void)'" However, there wasn't really
  a need to use the functor in the first place. 

- Got rid of a return that was after a break in a switch statement (pgi 
  errored about an unreachable statement)

- Initialized def to NULL (cray-prgenv-gnu errored saying 
  "loopInvariantCodeMotion.cpp:576:13: error: 'def' may be used uninitialized
  in this function [-Werror=maybe-uninitialized]"). That's not really true 
  since if there were no defs, the symExpr would have been in the 
  loopInvariantOperands list and the function would have returned, but 
  the compiler has no way of knowing that.

- Changed from while loop to do while loop. A do while loop is really the 
  behavior I wanted, but I did that by setting the oldNumInvariants to 
  unsigned max. However, I did that by setting oldNumInvariants to -1 (~0)
  which is pretty unclear and confusing. (And this caused an error for 
  cray-prgenv-gnu saying " warning: integer conversion resulted in a change 
  of sign"


git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@21619 3a8e244f-b0f2-452b-bcba-4c88e055c3ca