Remove the deprecation warnings for IO enums
In certain circumstances, I think when LastResortIO and IO are equally deep in
a use chain, instead of getting the proper deprecation warning we instead see:

error: symbol iomode is multiply defined
note: also defined as a function here (and possibly elsewhere)

This means that having the deprecation warning is not as useful as we would like
so remove it for the enums