comm-gasnet-ex.c: Fix the pshmInUse variable
This was causing unused variable warnings (and errors in `CHPL_DEVELOPER=1`) for non-ibv conduits, eg:
```
comm-gasnet-ex.c:730:18: error: 'pshmInUse' defined but not used [-Werror=unused-variable]
  730 | static chpl_bool pshmInUse = false;
      |                  ^~~~~~~~~
```
Fix the warning and fix verbose reporting to work correctly for all conduits.

Signed-off-by: bonachea <dobonachea@lbl.gov>