Fixing a bug and disallowing complex data types for bulk
* Bug fixed:

If a domain has int(32) indices there were a type casting issue inside
doiBulkTransfer. We just found two cases in 

        distributions/robust/arithmetic/basics/test_array_assignment.chpl
	distributions/robust/arithmetic/basics/test_infer_array_type.chpl

that use distributions/robust/arithmetic/driver.chpl where there is a domain like:
const Space2D32 = {n5-o5:int(32)..n5, n5-o5:int(32)..n5};

The compiler reported:

error: type mismatch in assignment from int(64) to int(32)
 
But now it's fixed.

* Complex disallowed

These FFT implementations are based on arrays of complex(128):

studies/hpcc/FFT/fft-candidate-2d.chpl
studies/hpcc/FFT/fft-hpcc06-mta.chpl
studies/hpcc/FFT/fft-hpcc06.chpl
studies/hpcc/FFT/bradc/fft.chpl
studies/hpcc/FFT/marybeth/fft.chpl
studies/hpcc/FFT/marybeth/fft-test-even.chpl
studies/hpcc/FFT/marybeth/fft2d.chpl

and they crash at run time inside the gasnet function called from our
doiBulkTransfer method. While we take a closer look at it, complex will
be disallowed.

Funny enough, the FFT version that I just committed (see r21156) uses
complex as well but works like a charm.

* Consistency improved

An additional minor change in order to improve consistency:
doiBulkTransferToDR required "a._value" as argument, while
doiBulkTransferFromDR just requires "a" (the chapel array). Now both of
them have the same prototype (using the array object as argument)



git-svn-id: http://svn.code.sf.net/p/chapel/code/branches/collaborations/bulkComms@21157 3a8e244f-b0f2-452b-bcba-4c88e055c3ca