Added a bug future for compiler reporting an error when a record is declared in another record or class.
In this case:

    record R {
      record Q {}
      proc pr { var q:Q; }
    }
    var r:R; r.pr;

I get:
    error: unresolved call '_construct_Q(outer=R)'
    note: candidates are: _construct_Q(_mt: _MT, outer: R)

Added other variations. When it is a class that's nested, things work fine.

nested-class-with-outer-1.chpl is a blend of nested-record-with-outer-1.chpl
and class_nest_simple.chpl.


git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@20053 3a8e244f-b0f2-452b-bcba-4c88e055c3ca