Early-in-week pass through REGRESSIONS file
I started my standard full sweep of REGRESSIONS against nightly logs (whether
reporting failures or not) to try and bring things up-to-date with the
present and found several cases that had not been noted or retired properly.
This should catch us up to today, approximately, the deltas being:

regress :(
----------
- undefined reference to chpl_bitops_debruijn64 with PGI compiler for new caching test
  (should now be fixed)
- Qthreads "worker unit does not exist" error on threadring (should now be fixed)
- verification failures for new --about tests (should now be fixed)
- freadComplex glibc failure 'invalid next size'
- portability issues with filerator test for most PrgEnvs
- asserteof failure for PGI (???)
- stable double free or corruption errors with freadIntFailed, fwriteIntFailed
- gcc warnings about assuming strict overflow

progress!
---------
+ retired regressions related to empty directories in git
+ removed long-since fixed ptrans timeouts from performance testing
+ removed long-since fixed pidigits-pretty2 memory leak issue
+ removed fast regressions related to gcc 4.3 (they probably still fail, but if we're
  not seeing them in testing, I don't think they belong here)
+ retired sudoku-reduce2 bug, which looks more TRIAGE than REGRESSION
+ retired build failures which are no longer failing
+ retired gcc 4.8 -Waggressive-loop-optimmizations problems which seem resolved
+ retired a number of gasnet.qthreads.numa issues which seem resolved

other
-----
* added a new section for VM-based performance runs
* re-sorted failures to match order in cron mailings
* ascribed memory leaks increase to r23794
* generally removed most timeouts since we've decided they belong more in TRIAGE,
  unless they were sufficiently consistent to raise concerns
* made gasnet.qthreads.flat inherit from GASNet rather than repeating known issues




git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@23870 3a8e244f-b0f2-452b-bcba-4c88e055c3ca