Fix network atomics for types not implemented in module code
We used to get compilation errors for real(32) network atomics and warnings for
8/16 bit int/uint atomics.

```chpl
// "error: Unsupported atomic type"
var a_r32: atomic real(32);

// "warning: Unsupported network atomic type" (and default to processor atomic)
var i_i8: atomic int(8);
```

Now we just default to processor atomics for real(32) and 8/16 bit integral
types without warning.

I think the old behavior was leftover from when you had to opt-into network
atomics instead of them being the default under ugni. And note that we actually
have runtime support for real(32) network atomics (implemented for real on
aries, and emulated with processor atomics on gemini) but there's no module
code yet.