fixed wide string invocation of string compare primitive
Added the new STRING_COMPARE primitive to the list of primitives for
which we need to dereference wide strings.  This should fix the
following GASNet regressions:

  Error: Timed out executing program multilocale/diten/nestedOn
  Error: Timed out executing program multilocale/diten/remoteString



git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@13865 3a8e244f-b0f2-452b-bcba-4c88e055c3ca