Fix bug in sub_test w/ multiple compopts + multiple file redirects in execopts
It turns out that sub_test.py has had a bug in which using a file
with multiple compopts and multiple execopts where the execopts
use different redirections resulted in an error like

  Error: a redirection file already exists:

This fixes the issue by moving the capture of the original redirect
default outside of the compopts loop, and resetting the redirect to
that original choice each time through.

Signed-off-by: Brad Chamberlain <bradcray@users.noreply.github.com>