Pre-release prep. Chapel 1.18.0: post-release version markings on master
NOTE: This is not Chapel release 1.18.0. This change prepares the source on
master branch for the upcoming Chapel 1.18.0 release, currently scheduled
for 20 Sep 2018.

Temporarily remove all "pre-release" version markings from master branch,
prior to creating the release/1.18 branch, so that all the release
version strings look like they should look in the final Chapel 1.18.0
release. The automated tests on master branch will be able to test the
final release.

Exception: doc/util/versionButton.php is not changed here.

After release/1.18 branch has been created, this change will be reversed
on master branch and most 1.18 version numbers will be bumped to 1.19.