Disabled folding of casts to reals (except of course from reals of the same size).
Removed a .future.

Changed the output to a test of the line

  param x : real = 1;

since coercion 1 to a real is no longer folded and thus x is assigned
a non-parameter value.  This gets the fairly good feedback:

  error: Initializing parameter 'x' to value not known at compile time


git-svn-id: http://svn.code.sf.net/p/chapel/code/trunk@9463 3a8e244f-b0f2-452b-bcba-4c88e055c3ca